name: openargo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  intl: ^0.16.1
  json_annotation: ^3.1.1
  sticky_grouped_list: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  pedantic: ^1.9.2

flutter:
  uses-material-design: true